/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kie.demo.taskassignment.test.insurance.misc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimReport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String name;
   private String address;
   private java.util.Date accidentDate;
   private String accidentDescription;

   private Boolean calculated;

   private Double amount;

   public ClaimReport()
   {
   }

   public String getName()
   {
      return this.name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getAddress()
   {
      return this.address;
   }

   public void setAddress(String address)
   {
      this.address = address;
   }

   public java.util.Date getAccidentDate()
   {
      return this.accidentDate;
   }

   public void setAccidentDate(java.util.Date accidentDate)
   {
      this.accidentDate = accidentDate;
   }

   public String getAccidentDescription()
   {
      return this.accidentDescription;
   }

   public void setAccidentDescription(String accidentDescription)
   {
      this.accidentDescription = accidentDescription;
   }

   public Boolean getCalculated()
   {
      return this.calculated;
   }

   public void setCalculated(Boolean calculated)
   {
      this.calculated = calculated;
   }

   public Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(Double amount)
   {
      this.amount = amount;
   }

   public ClaimReport(String name, String address,
         java.util.Date accidentDate, String accidentDescription,
         Boolean calculated, Double amount)
   {
      this.name = name;
      this.address = address;
      this.accidentDate = accidentDate;
      this.accidentDescription = accidentDescription;
      this.calculated = calculated;
      this.amount = amount;
   }

}